# Generated by Django 4.2.4 on 2023-08-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_Title', models.CharField(max_length=200)),
                ('Blog_Descripton', models.CharField(max_length=500)),
                ('Blog_Short_Description', models.CharField(max_length=255)),
                ('Blog_Image', models.ImageField(upload_to='blogs/')),
                ('Is_Home', models.BooleanField(default=False)),
                ('Is_Active', models.BooleanField(default=False)),
            ],
        ),
    ]
