# Generated by Django 4.2.4 on 2023-08-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='Blog_Descripton',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='Blog_Short_Description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='Blog_Title',
            field=models.CharField(max_length=500),
        ),
    ]
